// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: batch.proto

package protos;

public final class Batch {
  private Batch() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionBatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.TransactionBatch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 batchID = 1;</code>
     */
    int getBatchID();

    /**
     * <code>int32 senderID = 2;</code>
     */
    int getSenderID();

    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    java.util.List<protos.Batch.TransactionBatch.Transaction> 
        getTransactionsList();
    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    protos.Batch.TransactionBatch.Transaction getTransactions(int index);
    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    int getTransactionsCount();
    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    java.util.List<? extends protos.Batch.TransactionBatch.TransactionOrBuilder> 
        getTransactionsOrBuilderList();
    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    protos.Batch.TransactionBatch.TransactionOrBuilder getTransactionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protos.TransactionBatch}
   */
  public  static final class TransactionBatch extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.TransactionBatch)
      TransactionBatchOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionBatch.newBuilder() to construct.
    private TransactionBatch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionBatch() {
      batchID_ = 0;
      senderID_ = 0;
      transactions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionBatch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              batchID_ = input.readInt32();
              break;
            }
            case 16: {

              senderID_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                transactions_ = new java.util.ArrayList<protos.Batch.TransactionBatch.Transaction>();
                mutable_bitField0_ |= 0x00000004;
              }
              transactions_.add(
                  input.readMessage(protos.Batch.TransactionBatch.Transaction.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Batch.internal_static_protos_TransactionBatch_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Batch.internal_static_protos_TransactionBatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Batch.TransactionBatch.class, protos.Batch.TransactionBatch.Builder.class);
    }

    public interface TransactionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protos.TransactionBatch.Transaction)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 transactionID = 1;</code>
       */
      int getTransactionID();

      /**
       * <code>int32 accountNumber = 2;</code>
       */
      int getAccountNumber();

      /**
       * <code>int32 changeInSum = 3;</code>
       */
      int getChangeInSum();

      /**
       * <code>int32 a = 4;</code>
       */
      int getA();
    }
    /**
     * Protobuf type {@code protos.TransactionBatch.Transaction}
     */
    public  static final class Transaction extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protos.TransactionBatch.Transaction)
        TransactionOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Transaction.newBuilder() to construct.
      private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Transaction() {
        transactionID_ = 0;
        accountNumber_ = 0;
        changeInSum_ = 0;
        a_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Transaction(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                transactionID_ = input.readInt32();
                break;
              }
              case 16: {

                accountNumber_ = input.readInt32();
                break;
              }
              case 24: {

                changeInSum_ = input.readInt32();
                break;
              }
              case 32: {

                a_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Batch.internal_static_protos_TransactionBatch_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Batch.internal_static_protos_TransactionBatch_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Batch.TransactionBatch.Transaction.class, protos.Batch.TransactionBatch.Transaction.Builder.class);
      }

      public static final int TRANSACTIONID_FIELD_NUMBER = 1;
      private int transactionID_;
      /**
       * <code>int32 transactionID = 1;</code>
       */
      public int getTransactionID() {
        return transactionID_;
      }

      public static final int ACCOUNTNUMBER_FIELD_NUMBER = 2;
      private int accountNumber_;
      /**
       * <code>int32 accountNumber = 2;</code>
       */
      public int getAccountNumber() {
        return accountNumber_;
      }

      public static final int CHANGEINSUM_FIELD_NUMBER = 3;
      private int changeInSum_;
      /**
       * <code>int32 changeInSum = 3;</code>
       */
      public int getChangeInSum() {
        return changeInSum_;
      }

      public static final int A_FIELD_NUMBER = 4;
      private int a_;
      /**
       * <code>int32 a = 4;</code>
       */
      public int getA() {
        return a_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (transactionID_ != 0) {
          output.writeInt32(1, transactionID_);
        }
        if (accountNumber_ != 0) {
          output.writeInt32(2, accountNumber_);
        }
        if (changeInSum_ != 0) {
          output.writeInt32(3, changeInSum_);
        }
        if (a_ != 0) {
          output.writeInt32(4, a_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (transactionID_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, transactionID_);
        }
        if (accountNumber_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, accountNumber_);
        }
        if (changeInSum_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, changeInSum_);
        }
        if (a_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, a_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof protos.Batch.TransactionBatch.Transaction)) {
          return super.equals(obj);
        }
        protos.Batch.TransactionBatch.Transaction other = (protos.Batch.TransactionBatch.Transaction) obj;

        boolean result = true;
        result = result && (getTransactionID()
            == other.getTransactionID());
        result = result && (getAccountNumber()
            == other.getAccountNumber());
        result = result && (getChangeInSum()
            == other.getChangeInSum());
        result = result && (getA()
            == other.getA());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TRANSACTIONID_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionID();
        hash = (37 * hash) + ACCOUNTNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getAccountNumber();
        hash = (37 * hash) + CHANGEINSUM_FIELD_NUMBER;
        hash = (53 * hash) + getChangeInSum();
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static protos.Batch.TransactionBatch.Transaction parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protos.Batch.TransactionBatch.Transaction parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protos.Batch.TransactionBatch.Transaction parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protos.Batch.TransactionBatch.Transaction parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protos.Batch.TransactionBatch.Transaction parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protos.Batch.TransactionBatch.Transaction parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protos.Batch.TransactionBatch.Transaction parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protos.Batch.TransactionBatch.Transaction parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static protos.Batch.TransactionBatch.Transaction parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static protos.Batch.TransactionBatch.Transaction parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static protos.Batch.TransactionBatch.Transaction parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protos.Batch.TransactionBatch.Transaction parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(protos.Batch.TransactionBatch.Transaction prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protos.TransactionBatch.Transaction}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protos.TransactionBatch.Transaction)
          protos.Batch.TransactionBatch.TransactionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protos.Batch.internal_static_protos_TransactionBatch_Transaction_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protos.Batch.internal_static_protos_TransactionBatch_Transaction_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protos.Batch.TransactionBatch.Transaction.class, protos.Batch.TransactionBatch.Transaction.Builder.class);
        }

        // Construct using protos.Batch.TransactionBatch.Transaction.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          transactionID_ = 0;

          accountNumber_ = 0;

          changeInSum_ = 0;

          a_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protos.Batch.internal_static_protos_TransactionBatch_Transaction_descriptor;
        }

        public protos.Batch.TransactionBatch.Transaction getDefaultInstanceForType() {
          return protos.Batch.TransactionBatch.Transaction.getDefaultInstance();
        }

        public protos.Batch.TransactionBatch.Transaction build() {
          protos.Batch.TransactionBatch.Transaction result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public protos.Batch.TransactionBatch.Transaction buildPartial() {
          protos.Batch.TransactionBatch.Transaction result = new protos.Batch.TransactionBatch.Transaction(this);
          result.transactionID_ = transactionID_;
          result.accountNumber_ = accountNumber_;
          result.changeInSum_ = changeInSum_;
          result.a_ = a_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protos.Batch.TransactionBatch.Transaction) {
            return mergeFrom((protos.Batch.TransactionBatch.Transaction)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protos.Batch.TransactionBatch.Transaction other) {
          if (other == protos.Batch.TransactionBatch.Transaction.getDefaultInstance()) return this;
          if (other.getTransactionID() != 0) {
            setTransactionID(other.getTransactionID());
          }
          if (other.getAccountNumber() != 0) {
            setAccountNumber(other.getAccountNumber());
          }
          if (other.getChangeInSum() != 0) {
            setChangeInSum(other.getChangeInSum());
          }
          if (other.getA() != 0) {
            setA(other.getA());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protos.Batch.TransactionBatch.Transaction parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protos.Batch.TransactionBatch.Transaction) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int transactionID_ ;
        /**
         * <code>int32 transactionID = 1;</code>
         */
        public int getTransactionID() {
          return transactionID_;
        }
        /**
         * <code>int32 transactionID = 1;</code>
         */
        public Builder setTransactionID(int value) {
          
          transactionID_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 transactionID = 1;</code>
         */
        public Builder clearTransactionID() {
          
          transactionID_ = 0;
          onChanged();
          return this;
        }

        private int accountNumber_ ;
        /**
         * <code>int32 accountNumber = 2;</code>
         */
        public int getAccountNumber() {
          return accountNumber_;
        }
        /**
         * <code>int32 accountNumber = 2;</code>
         */
        public Builder setAccountNumber(int value) {
          
          accountNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 accountNumber = 2;</code>
         */
        public Builder clearAccountNumber() {
          
          accountNumber_ = 0;
          onChanged();
          return this;
        }

        private int changeInSum_ ;
        /**
         * <code>int32 changeInSum = 3;</code>
         */
        public int getChangeInSum() {
          return changeInSum_;
        }
        /**
         * <code>int32 changeInSum = 3;</code>
         */
        public Builder setChangeInSum(int value) {
          
          changeInSum_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 changeInSum = 3;</code>
         */
        public Builder clearChangeInSum() {
          
          changeInSum_ = 0;
          onChanged();
          return this;
        }

        private int a_ ;
        /**
         * <code>int32 a = 4;</code>
         */
        public int getA() {
          return a_;
        }
        /**
         * <code>int32 a = 4;</code>
         */
        public Builder setA(int value) {
          
          a_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 a = 4;</code>
         */
        public Builder clearA() {
          
          a_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protos.TransactionBatch.Transaction)
      }

      // @@protoc_insertion_point(class_scope:protos.TransactionBatch.Transaction)
      private static final protos.Batch.TransactionBatch.Transaction DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new protos.Batch.TransactionBatch.Transaction();
      }

      public static protos.Batch.TransactionBatch.Transaction getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Transaction>
          PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
        public Transaction parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Transaction(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Transaction> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Transaction> getParserForType() {
        return PARSER;
      }

      public protos.Batch.TransactionBatch.Transaction getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int BATCHID_FIELD_NUMBER = 1;
    private int batchID_;
    /**
     * <code>int32 batchID = 1;</code>
     */
    public int getBatchID() {
      return batchID_;
    }

    public static final int SENDERID_FIELD_NUMBER = 2;
    private int senderID_;
    /**
     * <code>int32 senderID = 2;</code>
     */
    public int getSenderID() {
      return senderID_;
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 3;
    private java.util.List<protos.Batch.TransactionBatch.Transaction> transactions_;
    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    public java.util.List<protos.Batch.TransactionBatch.Transaction> getTransactionsList() {
      return transactions_;
    }
    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    public java.util.List<? extends protos.Batch.TransactionBatch.TransactionOrBuilder> 
        getTransactionsOrBuilderList() {
      return transactions_;
    }
    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    public int getTransactionsCount() {
      return transactions_.size();
    }
    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    public protos.Batch.TransactionBatch.Transaction getTransactions(int index) {
      return transactions_.get(index);
    }
    /**
     * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
     */
    public protos.Batch.TransactionBatch.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      return transactions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (batchID_ != 0) {
        output.writeInt32(1, batchID_);
      }
      if (senderID_ != 0) {
        output.writeInt32(2, senderID_);
      }
      for (int i = 0; i < transactions_.size(); i++) {
        output.writeMessage(3, transactions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (batchID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, batchID_);
      }
      if (senderID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, senderID_);
      }
      for (int i = 0; i < transactions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, transactions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Batch.TransactionBatch)) {
        return super.equals(obj);
      }
      protos.Batch.TransactionBatch other = (protos.Batch.TransactionBatch) obj;

      boolean result = true;
      result = result && (getBatchID()
          == other.getBatchID());
      result = result && (getSenderID()
          == other.getSenderID());
      result = result && getTransactionsList()
          .equals(other.getTransactionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BATCHID_FIELD_NUMBER;
      hash = (53 * hash) + getBatchID();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderID();
      if (getTransactionsCount() > 0) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Batch.TransactionBatch parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Batch.TransactionBatch parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Batch.TransactionBatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Batch.TransactionBatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Batch.TransactionBatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Batch.TransactionBatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Batch.TransactionBatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Batch.TransactionBatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Batch.TransactionBatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Batch.TransactionBatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Batch.TransactionBatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Batch.TransactionBatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Batch.TransactionBatch prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.TransactionBatch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.TransactionBatch)
        protos.Batch.TransactionBatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Batch.internal_static_protos_TransactionBatch_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Batch.internal_static_protos_TransactionBatch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Batch.TransactionBatch.class, protos.Batch.TransactionBatch.Builder.class);
      }

      // Construct using protos.Batch.TransactionBatch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTransactionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        batchID_ = 0;

        senderID_ = 0;

        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Batch.internal_static_protos_TransactionBatch_descriptor;
      }

      public protos.Batch.TransactionBatch getDefaultInstanceForType() {
        return protos.Batch.TransactionBatch.getDefaultInstance();
      }

      public protos.Batch.TransactionBatch build() {
        protos.Batch.TransactionBatch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protos.Batch.TransactionBatch buildPartial() {
        protos.Batch.TransactionBatch result = new protos.Batch.TransactionBatch(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.batchID_ = batchID_;
        result.senderID_ = senderID_;
        if (transactionsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            transactions_ = java.util.Collections.unmodifiableList(transactions_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.transactions_ = transactions_;
        } else {
          result.transactions_ = transactionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Batch.TransactionBatch) {
          return mergeFrom((protos.Batch.TransactionBatch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Batch.TransactionBatch other) {
        if (other == protos.Batch.TransactionBatch.getDefaultInstance()) return this;
        if (other.getBatchID() != 0) {
          setBatchID(other.getBatchID());
        }
        if (other.getSenderID() != 0) {
          setSenderID(other.getSenderID());
        }
        if (transactionsBuilder_ == null) {
          if (!other.transactions_.isEmpty()) {
            if (transactions_.isEmpty()) {
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTransactionsIsMutable();
              transactions_.addAll(other.transactions_);
            }
            onChanged();
          }
        } else {
          if (!other.transactions_.isEmpty()) {
            if (transactionsBuilder_.isEmpty()) {
              transactionsBuilder_.dispose();
              transactionsBuilder_ = null;
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000004);
              transactionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTransactionsFieldBuilder() : null;
            } else {
              transactionsBuilder_.addAllMessages(other.transactions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Batch.TransactionBatch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Batch.TransactionBatch) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int batchID_ ;
      /**
       * <code>int32 batchID = 1;</code>
       */
      public int getBatchID() {
        return batchID_;
      }
      /**
       * <code>int32 batchID = 1;</code>
       */
      public Builder setBatchID(int value) {
        
        batchID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 batchID = 1;</code>
       */
      public Builder clearBatchID() {
        
        batchID_ = 0;
        onChanged();
        return this;
      }

      private int senderID_ ;
      /**
       * <code>int32 senderID = 2;</code>
       */
      public int getSenderID() {
        return senderID_;
      }
      /**
       * <code>int32 senderID = 2;</code>
       */
      public Builder setSenderID(int value) {
        
        senderID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 senderID = 2;</code>
       */
      public Builder clearSenderID() {
        
        senderID_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<protos.Batch.TransactionBatch.Transaction> transactions_ =
        java.util.Collections.emptyList();
      private void ensureTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          transactions_ = new java.util.ArrayList<protos.Batch.TransactionBatch.Transaction>(transactions_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.Batch.TransactionBatch.Transaction, protos.Batch.TransactionBatch.Transaction.Builder, protos.Batch.TransactionBatch.TransactionOrBuilder> transactionsBuilder_;

      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public java.util.List<protos.Batch.TransactionBatch.Transaction> getTransactionsList() {
        if (transactionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transactions_);
        } else {
          return transactionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public int getTransactionsCount() {
        if (transactionsBuilder_ == null) {
          return transactions_.size();
        } else {
          return transactionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public protos.Batch.TransactionBatch.Transaction getTransactions(int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);
        } else {
          return transactionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public Builder setTransactions(
          int index, protos.Batch.TransactionBatch.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.set(index, value);
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public Builder setTransactions(
          int index, protos.Batch.TransactionBatch.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.set(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public Builder addTransactions(protos.Batch.TransactionBatch.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public Builder addTransactions(
          int index, protos.Batch.TransactionBatch.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(index, value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public Builder addTransactions(
          protos.Batch.TransactionBatch.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public Builder addTransactions(
          int index, protos.Batch.TransactionBatch.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public Builder addAllTransactions(
          java.lang.Iterable<? extends protos.Batch.TransactionBatch.Transaction> values) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, transactions_);
          onChanged();
        } else {
          transactionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public Builder clearTransactions() {
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public Builder removeTransactions(int index) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.remove(index);
          onChanged();
        } else {
          transactionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public protos.Batch.TransactionBatch.Transaction.Builder getTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public protos.Batch.TransactionBatch.TransactionOrBuilder getTransactionsOrBuilder(
          int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);  } else {
          return transactionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public java.util.List<? extends protos.Batch.TransactionBatch.TransactionOrBuilder> 
           getTransactionsOrBuilderList() {
        if (transactionsBuilder_ != null) {
          return transactionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transactions_);
        }
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public protos.Batch.TransactionBatch.Transaction.Builder addTransactionsBuilder() {
        return getTransactionsFieldBuilder().addBuilder(
            protos.Batch.TransactionBatch.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public protos.Batch.TransactionBatch.Transaction.Builder addTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().addBuilder(
            index, protos.Batch.TransactionBatch.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.TransactionBatch.Transaction transactions = 3;</code>
       */
      public java.util.List<protos.Batch.TransactionBatch.Transaction.Builder> 
           getTransactionsBuilderList() {
        return getTransactionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.Batch.TransactionBatch.Transaction, protos.Batch.TransactionBatch.Transaction.Builder, protos.Batch.TransactionBatch.TransactionOrBuilder> 
          getTransactionsFieldBuilder() {
        if (transactionsBuilder_ == null) {
          transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protos.Batch.TransactionBatch.Transaction, protos.Batch.TransactionBatch.Transaction.Builder, protos.Batch.TransactionBatch.TransactionOrBuilder>(
                  transactions_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          transactions_ = null;
        }
        return transactionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.TransactionBatch)
    }

    // @@protoc_insertion_point(class_scope:protos.TransactionBatch)
    private static final protos.Batch.TransactionBatch DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Batch.TransactionBatch();
    }

    public static protos.Batch.TransactionBatch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionBatch>
        PARSER = new com.google.protobuf.AbstractParser<TransactionBatch>() {
      public TransactionBatch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionBatch(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionBatch> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionBatch> getParserForType() {
      return PARSER;
    }

    public protos.Batch.TransactionBatch getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientBalanceQueryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.ClientBalanceQuery)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 clientID = 1;</code>
     */
    int getClientID();
  }
  /**
   * Protobuf type {@code protos.ClientBalanceQuery}
   */
  public  static final class ClientBalanceQuery extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.ClientBalanceQuery)
      ClientBalanceQueryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientBalanceQuery.newBuilder() to construct.
    private ClientBalanceQuery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientBalanceQuery() {
      clientID_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientBalanceQuery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              clientID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Batch.internal_static_protos_ClientBalanceQuery_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Batch.internal_static_protos_ClientBalanceQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Batch.ClientBalanceQuery.class, protos.Batch.ClientBalanceQuery.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private int clientID_;
    /**
     * <code>int32 clientID = 1;</code>
     */
    public int getClientID() {
      return clientID_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientID_ != 0) {
        output.writeInt32(1, clientID_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clientID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Batch.ClientBalanceQuery)) {
        return super.equals(obj);
      }
      protos.Batch.ClientBalanceQuery other = (protos.Batch.ClientBalanceQuery) obj;

      boolean result = true;
      result = result && (getClientID()
          == other.getClientID());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientID();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Batch.ClientBalanceQuery parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Batch.ClientBalanceQuery parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Batch.ClientBalanceQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Batch.ClientBalanceQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Batch.ClientBalanceQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Batch.ClientBalanceQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Batch.ClientBalanceQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Batch.ClientBalanceQuery prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.ClientBalanceQuery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.ClientBalanceQuery)
        protos.Batch.ClientBalanceQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Batch.internal_static_protos_ClientBalanceQuery_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Batch.internal_static_protos_ClientBalanceQuery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Batch.ClientBalanceQuery.class, protos.Batch.ClientBalanceQuery.Builder.class);
      }

      // Construct using protos.Batch.ClientBalanceQuery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientID_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Batch.internal_static_protos_ClientBalanceQuery_descriptor;
      }

      public protos.Batch.ClientBalanceQuery getDefaultInstanceForType() {
        return protos.Batch.ClientBalanceQuery.getDefaultInstance();
      }

      public protos.Batch.ClientBalanceQuery build() {
        protos.Batch.ClientBalanceQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protos.Batch.ClientBalanceQuery buildPartial() {
        protos.Batch.ClientBalanceQuery result = new protos.Batch.ClientBalanceQuery(this);
        result.clientID_ = clientID_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Batch.ClientBalanceQuery) {
          return mergeFrom((protos.Batch.ClientBalanceQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Batch.ClientBalanceQuery other) {
        if (other == protos.Batch.ClientBalanceQuery.getDefaultInstance()) return this;
        if (other.getClientID() != 0) {
          setClientID(other.getClientID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Batch.ClientBalanceQuery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Batch.ClientBalanceQuery) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int clientID_ ;
      /**
       * <code>int32 clientID = 1;</code>
       */
      public int getClientID() {
        return clientID_;
      }
      /**
       * <code>int32 clientID = 1;</code>
       */
      public Builder setClientID(int value) {
        
        clientID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 clientID = 1;</code>
       */
      public Builder clearClientID() {
        
        clientID_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.ClientBalanceQuery)
    }

    // @@protoc_insertion_point(class_scope:protos.ClientBalanceQuery)
    private static final protos.Batch.ClientBalanceQuery DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Batch.ClientBalanceQuery();
    }

    public static protos.Batch.ClientBalanceQuery getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientBalanceQuery>
        PARSER = new com.google.protobuf.AbstractParser<ClientBalanceQuery>() {
      public ClientBalanceQuery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientBalanceQuery(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientBalanceQuery> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientBalanceQuery> getParserForType() {
      return PARSER;
    }

    public protos.Batch.ClientBalanceQuery getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientBalanceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.ClientBalanceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 balance = 1;</code>
     */
    int getBalance();
  }
  /**
   * Protobuf type {@code protos.ClientBalanceResponse}
   */
  public  static final class ClientBalanceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.ClientBalanceResponse)
      ClientBalanceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientBalanceResponse.newBuilder() to construct.
    private ClientBalanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientBalanceResponse() {
      balance_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientBalanceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              balance_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Batch.internal_static_protos_ClientBalanceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Batch.internal_static_protos_ClientBalanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Batch.ClientBalanceResponse.class, protos.Batch.ClientBalanceResponse.Builder.class);
    }

    public static final int BALANCE_FIELD_NUMBER = 1;
    private int balance_;
    /**
     * <code>int32 balance = 1;</code>
     */
    public int getBalance() {
      return balance_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (balance_ != 0) {
        output.writeInt32(1, balance_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (balance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, balance_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Batch.ClientBalanceResponse)) {
        return super.equals(obj);
      }
      protos.Batch.ClientBalanceResponse other = (protos.Batch.ClientBalanceResponse) obj;

      boolean result = true;
      result = result && (getBalance()
          == other.getBalance());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getBalance();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Batch.ClientBalanceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Batch.ClientBalanceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Batch.ClientBalanceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Batch.ClientBalanceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Batch.ClientBalanceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Batch.ClientBalanceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Batch.ClientBalanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Batch.ClientBalanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Batch.ClientBalanceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.ClientBalanceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.ClientBalanceResponse)
        protos.Batch.ClientBalanceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Batch.internal_static_protos_ClientBalanceResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Batch.internal_static_protos_ClientBalanceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Batch.ClientBalanceResponse.class, protos.Batch.ClientBalanceResponse.Builder.class);
      }

      // Construct using protos.Batch.ClientBalanceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        balance_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Batch.internal_static_protos_ClientBalanceResponse_descriptor;
      }

      public protos.Batch.ClientBalanceResponse getDefaultInstanceForType() {
        return protos.Batch.ClientBalanceResponse.getDefaultInstance();
      }

      public protos.Batch.ClientBalanceResponse build() {
        protos.Batch.ClientBalanceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protos.Batch.ClientBalanceResponse buildPartial() {
        protos.Batch.ClientBalanceResponse result = new protos.Batch.ClientBalanceResponse(this);
        result.balance_ = balance_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Batch.ClientBalanceResponse) {
          return mergeFrom((protos.Batch.ClientBalanceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Batch.ClientBalanceResponse other) {
        if (other == protos.Batch.ClientBalanceResponse.getDefaultInstance()) return this;
        if (other.getBalance() != 0) {
          setBalance(other.getBalance());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Batch.ClientBalanceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Batch.ClientBalanceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int balance_ ;
      /**
       * <code>int32 balance = 1;</code>
       */
      public int getBalance() {
        return balance_;
      }
      /**
       * <code>int32 balance = 1;</code>
       */
      public Builder setBalance(int value) {
        
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 balance = 1;</code>
       */
      public Builder clearBalance() {
        
        balance_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.ClientBalanceResponse)
    }

    // @@protoc_insertion_point(class_scope:protos.ClientBalanceResponse)
    private static final protos.Batch.ClientBalanceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Batch.ClientBalanceResponse();
    }

    public static protos.Batch.ClientBalanceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientBalanceResponse>
        PARSER = new com.google.protobuf.AbstractParser<ClientBalanceResponse>() {
      public ClientBalanceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientBalanceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientBalanceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientBalanceResponse> getParserForType() {
      return PARSER;
    }

    public protos.Batch.ClientBalanceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_TransactionBatch_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_TransactionBatch_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_TransactionBatch_Transaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_TransactionBatch_Transaction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ClientBalanceQuery_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ClientBalanceQuery_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ClientBalanceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ClientBalanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013batch.proto\022\006protos\032\033google/protobuf/e" +
      "mpty.proto\032\034google/api/annotations.proto" +
      "\"\316\001\n\020TransactionBatch\022\017\n\007batchID\030\001 \001(\005\022\020" +
      "\n\010senderID\030\002 \001(\005\022:\n\014transactions\030\003 \003(\0132$" +
      ".protos.TransactionBatch.Transaction\032[\n\013" +
      "Transaction\022\025\n\rtransactionID\030\001 \001(\005\022\025\n\rac" +
      "countNumber\030\002 \001(\005\022\023\n\013changeInSum\030\003 \001(\005\022\t" +
      "\n\001a\030\004 \001(\005\"&\n\022ClientBalanceQuery\022\020\n\010clien" +
      "tID\030\001 \001(\005\"(\n\025ClientBalanceResponse\022\017\n\007ba" +
      "lance\030\001 \001(\0052N\n\013BatchSender\022?\n\tSendBatch\022" +
      "\030.protos.TransactionBatch\032\026.google.proto" +
      "buf.Empty\"\0002\310\001\n\023ClientRESTInterface\022g\n\ng" +
      "etBalance\022\032.protos.ClientBalanceQuery\032\035." +
      "protos.ClientBalanceResponse\"\036\202\323\344\223\002\030\022\026/v" +
      "1/payload/{clientID}\022H\n\004Ping\022\026.google.pr" +
      "otobuf.Empty\032\026.google.protobuf.Empty\"\020\202\323" +
      "\344\223\002\n\022\010/v1/pingb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_protos_TransactionBatch_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_TransactionBatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_TransactionBatch_descriptor,
        new java.lang.String[] { "BatchID", "SenderID", "Transactions", });
    internal_static_protos_TransactionBatch_Transaction_descriptor =
      internal_static_protos_TransactionBatch_descriptor.getNestedTypes().get(0);
    internal_static_protos_TransactionBatch_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_TransactionBatch_Transaction_descriptor,
        new java.lang.String[] { "TransactionID", "AccountNumber", "ChangeInSum", "A", });
    internal_static_protos_ClientBalanceQuery_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_ClientBalanceQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ClientBalanceQuery_descriptor,
        new java.lang.String[] { "ClientID", });
    internal_static_protos_ClientBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_ClientBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ClientBalanceResponse_descriptor,
        new java.lang.String[] { "Balance", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
